[package]
name = "hed"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
color-eyre = "0.5.11"
regex = "1.5.4"
termion = "1.5.6"
